### ISSUE TITLE
Bug: Hello i can not Open a scratchcard

### ISSUE THREAD

**Issue by GGamer97** [solareon/slrn_scratchcard#1]
Hello i can not Open a scratchcard. I have a Error
![222](https://github.com/solareon/slrn_scratchcard/assets/167695781/2b73faad-8183-46ea-b765-18c84779ed8a)

**Comment by solareon** [comment]
You need to build the ui or download the release version here https://github.com/solareon/slrn_scratchcard/releases

**Comment by GGamer97** [comment]
Thanks for helping :D Now it is working :D
